Repository SU-SWS/stanford_basic, pull requests merged in 2020-09, with the labels that each got.

#177 D8CORE-2562: Update option A line-height to prevent overlap.
  dist/css/components.css
  src/scss/components/lockup/_lockup.scss
  src/scss/components/masthead/_wrapper.scss
Labels: size/xs

#178 D8CORE-2490: Alert Component Updates
  .nvmrc
  dist/assets/fonts/fa-brands-400.eot
  dist/assets/fonts/fa-brands-400.ttf
  dist/assets/fonts/fa-brands-400.woff
  dist/assets/fonts/fa-brands-400.woff2
  dist/assets/fonts/fa-regular-400.eot
  dist/assets/fonts/fa-regular-400.ttf
  dist/assets/fonts/fa-regular-400.woff
  dist/assets/fonts/fa-regular-400.woff2
  dist/assets/fonts/fa-solid-900.eot
  dist/assets/fonts/fa-solid-900.ttf
  dist/assets/fonts/fa-solid-900.woff
  dist/assets/fonts/fa-solid-900.woff2
  dist/assets/img/alert-error.png
  dist/assets/img/alert-info.png
  dist/assets/img/alert-success.png
  dist/assets/img/alert-warning.png
  dist/assets/svg/alert-error.svg
  dist/assets/svg/alert-info.svg
  dist/assets/svg/alert-success.svg
  dist/assets/svg/alert-warning.svg
  dist/assets/svg/fa-brands-400.svg
  dist/assets/svg/fa-regular-400.svg
  dist/assets/svg/fa-solid-900.svg
  dist/css/base.css
  dist/css/ckeditor.css
  dist/css/components.css
  dist/css/state.css
  dist/js/base.js
  dist/js/behaviors.js
  dist/templates/decanter/components/alert/alert.twig
  dist/templates/decanter/components/brand-bar/brand-bar.twig
  dist/templates/decanter/components/global-footer/global-footer.twig
  dist/templates/decanter/components/local-footer/local-footer.twig
  dist/templates/decanter/components/site-search/site-search.twig
  package-lock.json
  package.json
  stanford_basic.theme
  templates/core/status-messages.html.twig
Labels: A11y-test, size/xl

#180 Update Decanter to v 6.1.1 and compile.
  dist/css/base.css
  dist/css/components.css
  dist/templates/decanter/components/local-footer/local-footer.twig
  package-lock.json
  package.json
  src/scss/components/alert/_alert--info.scss
Labels: size/xs

#181 D8CORE-2454: Lockup default array structure mis-match fix.
  dist/css/base.css
  package-lock.json
  package.json
  stanford_basic.theme
Labels: size/xs

#182 "8.x-4.x > 8.4.10
  .nvmrc
  CHANGELOG.md
  composer.json
  dist/assets/fonts/fa-brands-400.eot
  dist/assets/fonts/fa-brands-400.ttf
  dist/assets/fonts/fa-brands-400.woff
  dist/assets/fonts/fa-brands-400.woff2
  dist/assets/fonts/fa-regular-400.eot
  dist/assets/fonts/fa-regular-400.ttf
  dist/assets/fonts/fa-regular-400.woff
  dist/assets/fonts/fa-regular-400.woff2
  dist/assets/fonts/fa-solid-900.eot
  dist/assets/fonts/fa-solid-900.ttf
  dist/assets/fonts/fa-solid-900.woff
  dist/assets/fonts/fa-solid-900.woff2
  dist/assets/img/alert-error.png
  dist/assets/img/alert-info.png
  dist/assets/img/alert-success.png
  dist/assets/img/alert-warning.png
  dist/assets/svg/alert-error.svg
  dist/assets/svg/alert-info.svg
  dist/assets/svg/alert-success.svg
  dist/assets/svg/alert-warning.svg
  dist/assets/svg/fa-brands-400.svg
  dist/assets/svg/fa-regular-400.svg
  dist/assets/svg/fa-solid-900.svg
  dist/css/base.css
  dist/css/ckeditor.css
  dist/css/components.css
  dist/css/state.css
  dist/js/base.js
  dist/js/behaviors.js
  dist/templates/decanter/components/alert/alert.twig
  dist/templates/decanter/components/brand-bar/brand-bar.twig
  dist/templates/decanter/components/global-footer/global-footer.twig
  dist/templates/decanter/components/local-footer/local-footer.twig
  dist/templates/decanter/components/site-search/site-search.twig
  package-lock.json
  package.json
  src/scss/components/alert/_alert--info.scss
  src/scss/components/lockup/_lockup.scss
  src/scss/components/masthead/_wrapper.scss
  stanford_basic.info.yml
  stanford_basic.theme
  templates/core/status-messages.html.twig
  templates/page.html.twig
Labels: patch, size/xl

#184 D8CORE-000: Protection from null object in menu
  stanford_basic.theme
Labels: size/xs

#185 D8CORE-2565: adding margin below the secondary menu
  dist/css/components.css
  src/scss/components/secondary-nav/_secondary-nav.scss
Labels: size/xs

#187 Edits.
  templates/content/media.html.twig
  templates/core/status-messages.html.twig
  templates/html.html.twig
  templates/node.html.twig
  templates/page--user--login.html.twig
  templates/page.html.twig
  templates/region.html.twig
  templates/search/search-result--node-search.html.twig
Labels: size/s
