Repository SU-SWS/stanford_basic, pull requests merged in 2020-12, with the labels that each got.

#202 D8CORE-2268: adjusting the spacing for media files in the wysiwyg and fixing the centering for the pdf.
  dist/css/components.css
  src/scss/components/wysiwyg/_media.scss
Labels: size/xs

#204 "8.x-4.x 8.4.14
  CHANGELOG.md
  UPGRADE.md
  composer.json
  dist/css/base.css
  dist/css/ckeditor.css
  dist/css/components.css
  dist/templates/decanter/components/media/media.twig
  package-lock.json
  package.json
  src/scss/components/wysiwyg/_line_length.scss
  src/scss/components/wysiwyg/_media.scss
  stanford_basic.info.yml
  stanford_basic.theme
Labels: patch, size/m

#203 Use stable9 for drupal9
  UPGRADE.md
  composer.json
  stanford_basic.info.yml
  templates/core/field.html.twig
  templates/navigation/toolbar.html.twig
Labels: patch, size/xs
