Repository SU-SWS/stanford_basic, pull requests merged in 2020-07, with the labels that each got.

#168 D8CORE-1406: remove link, move page-content ID
  templates/page--user--login.html.twig
  templates/page.html.twig
Labels: size/xs

#171 8.4.8
  CHANGELOG.md
  stanford_basic.info.yml
  templates/page--user--login.html.twig
  templates/page.html.twig
Labels: patch, size/xs

#166 D8CORE-1410: Back to site link
  dist/css/theme.css
  dist/js/behaviors.js
  src/js/stanford_basic.behavior.js
  src/scss/theme/menu/_local-tasks.scss
  stanford_basic.theme
  templates/menus/menu-local-tasks.html.twig
Labels: patch, size/xs

#170 D8CORE-1472: Updates to lockup settings for logo support
  dist/css/components.css
  dist/css/state.css
  dist/js/behaviors.js
  package-lock.json
  package.json
  src/scss/components/index.scss
  src/scss/components/lockup/_lockup.scss
  src/scss/components/lockup/index.scss
  src/scss/state/_hidden.scss
  src/scss/state/index.scss
  stanford_basic.theme
  templates/block/block--system-branding-block.html.twig
  theme-settings.php
Labels: size/l
