Repository SU-SWS/stanford_basic, pull requests merged in 2020-06, with the labels that each got.

#164 D8CORE-2189: Update to Decanter 6.0.6
  dist/assets/fonts/fa-brands-400.eot
  dist/assets/fonts/fa-brands-400.ttf
  dist/assets/fonts/fa-brands-400.woff
  dist/assets/fonts/fa-brands-400.woff2
  dist/assets/fonts/fa-regular-400.eot
  dist/assets/fonts/fa-regular-400.ttf
  dist/assets/fonts/fa-regular-400.woff
  dist/assets/fonts/fa-regular-400.woff2
  dist/assets/img/check.png
  dist/assets/svg/fa-brands-400.svg
  dist/assets/svg/fa-regular-400.svg
  dist/css/base.css
  dist/js/base.js
  dist/js/behaviors.js
  dist/templates/decanter/components/accordion/accordion.twig
  dist/templates/decanter/components/main-nav/main-nav.twig
  dist/templates/decanter/components/quote/quote.twig
  package-lock.json
  package.json
  templates/menus/macros/nav-menu.twig
  templates/menus/macros/secondary-nav-menu.twig
Labels: size/xl

#165 D8CORE-000 Provide a default lockup option
  stanford_basic.theme
Labels: size/xs

#167 "8.x-4.x > 8.4.7
  CHANGELOG.md
  dist/assets/fonts/fa-brands-400.eot
  dist/assets/fonts/fa-brands-400.ttf
  dist/assets/fonts/fa-brands-400.woff
  dist/assets/fonts/fa-brands-400.woff2
  dist/assets/fonts/fa-regular-400.eot
  dist/assets/fonts/fa-regular-400.ttf
  dist/assets/fonts/fa-regular-400.woff
  dist/assets/fonts/fa-regular-400.woff2
  dist/assets/img/check.png
  dist/assets/svg/fa-brands-400.svg
  dist/assets/svg/fa-regular-400.svg
  dist/css/base.css
  dist/js/base.js
  dist/js/behaviors.js
  dist/templates/decanter/components/accordion/accordion.twig
  dist/templates/decanter/components/main-nav/main-nav.twig
  dist/templates/decanter/components/quote/quote.twig
  package-lock.json
  package.json
  stanford_basic.info.yml
  stanford_basic.theme
  templates/menus/macros/nav-menu.twig
  templates/menus/macros/secondary-nav-menu.twig
Labels: patch, size/xl
