Repository SU-SWS/stanford_basic, pull requests merged in 2020-10, with the labels that each got.

#183 Add blocks for extending stanford_basic
  templates/content/media.html.twig
  templates/core/status-messages.html.twig
  templates/html.html.twig
  templates/node.html.twig
  templates/page--user--login.html.twig
  templates/page.html.twig
  templates/region.html.twig
  templates/search/search-result--node-search.html.twig
Labels: size/s

#188 updating-decanter: Needed to update decanter.
  dist/assets/fonts/fa-brands-400.eot
  dist/assets/fonts/fa-brands-400.ttf
  dist/assets/fonts/fa-brands-400.woff
  dist/assets/fonts/fa-brands-400.woff2
  dist/assets/fonts/fa-regular-400.eot
  dist/assets/fonts/fa-regular-400.ttf
  dist/assets/fonts/fa-regular-400.woff
  dist/assets/fonts/fa-regular-400.woff2
  dist/assets/fonts/fa-solid-900.eot
  dist/assets/fonts/fa-solid-900.ttf
  dist/assets/fonts/fa-solid-900.woff
  dist/assets/fonts/fa-solid-900.woff2
  dist/assets/svg/fa-brands-400.svg
  dist/assets/svg/fa-regular-400.svg
  dist/assets/svg/fa-solid-900.svg
  dist/css/base.css
  dist/templates/decanter/components/global-footer/global-footer.twig
  dist/templates/decanter/components/media/media.twig
Labels: size/s

#189 8.4.11
  CHANGELOG.md
  dist/assets/fonts/fa-brands-400.eot
  dist/assets/fonts/fa-brands-400.ttf
  dist/assets/fonts/fa-brands-400.woff
  dist/assets/fonts/fa-brands-400.woff2
  dist/assets/fonts/fa-regular-400.eot
  dist/assets/fonts/fa-regular-400.ttf
  dist/assets/fonts/fa-regular-400.woff
  dist/assets/fonts/fa-regular-400.woff2
  dist/assets/fonts/fa-solid-900.eot
  dist/assets/fonts/fa-solid-900.ttf
  dist/assets/fonts/fa-solid-900.woff
  dist/assets/fonts/fa-solid-900.woff2
  dist/assets/svg/fa-brands-400.svg
  dist/assets/svg/fa-regular-400.svg
  dist/assets/svg/fa-solid-900.svg
  dist/css/base.css
  dist/css/components.css
  dist/templates/decanter/components/global-footer/global-footer.twig
  dist/templates/decanter/components/media/media.twig
  src/scss/components/secondary-nav/_secondary-nav.scss
  stanford_basic.info.yml
  stanford_basic.theme
  templates/content/media.html.twig
  templates/core/status-messages.html.twig
  templates/html.html.twig
  templates/node.html.twig
  templates/page--user--login.html.twig
  templates/page.html.twig
  templates/region.html.twig
  templates/search/search-result--node-search.html.twig
Labels: patch, size/s

#191 D8CORE-1366: Added tooltips to menu items which have a `description` set.
  templates/menus/macros/nav-menu.twig
Labels: size/xs

#148 D8CORE-1073: A new way to move the search box into the mobile menu
  dist/assets/fonts/fa-brands-400.eot
  dist/assets/fonts/fa-brands-400.ttf
  dist/assets/fonts/fa-brands-400.woff
  dist/assets/fonts/fa-brands-400.woff2
  dist/assets/fonts/fa-regular-400.eot
  dist/assets/fonts/fa-regular-400.ttf
  dist/assets/fonts/fa-regular-400.woff
  dist/assets/fonts/fa-regular-400.woff2
  dist/assets/fonts/fa-solid-900.eot
  dist/assets/fonts/fa-solid-900.ttf
  dist/assets/fonts/fa-solid-900.woff
  dist/assets/fonts/fa-solid-900.woff2
  dist/assets/svg/fa-brands-400.svg
  dist/assets/svg/fa-regular-400.svg
  dist/assets/svg/fa-solid-900.svg
  dist/css/components.css
  dist/js/behaviors.js
  src/js/stanford_basic.behavior.js
  src/scss/components/multi-menu/_multi-menu.scss
Labels: a11y, size/xs
