Repository SU-SWS/stanford_basic, pull requests merged in 2020-11, with the labels that each got.

#190 D8CORE-2102: Add check to see if the path is part of the url
  stanford_basic.theme
Labels: size/xs

#197 "8.x-4.x 8.4.12
  CHANGELOG.md
  dist/assets/fonts/fa-brands-400.eot
  dist/assets/fonts/fa-brands-400.ttf
  dist/assets/fonts/fa-brands-400.woff
  dist/assets/fonts/fa-brands-400.woff2
  dist/assets/fonts/fa-regular-400.eot
  dist/assets/fonts/fa-regular-400.ttf
  dist/assets/fonts/fa-regular-400.woff
  dist/assets/fonts/fa-regular-400.woff2
  dist/assets/fonts/fa-solid-900.eot
  dist/assets/fonts/fa-solid-900.ttf
  dist/assets/fonts/fa-solid-900.woff
  dist/assets/fonts/fa-solid-900.woff2
  dist/assets/svg/fa-brands-400.svg
  dist/assets/svg/fa-regular-400.svg
  dist/assets/svg/fa-solid-900.svg
  dist/css/components.css
  dist/js/base.js
  dist/js/behaviors.js
  package-lock.json
  package.json
  src/js/components/secondary-nav/buttons/SecondarySubNavButtons.js
  src/js/stanford_basic.behavior.js
  src/scss/components/multi-menu/_multi-menu.scss
  stanford_basic.info.yml
  stanford_basic.theme
  templates/menus/macros/nav-menu.twig
Labels: patch

#199 Hotfix: Removed code that matched partials paths
  CHANGELOG.md
  stanford_basic.info.yml
  stanford_basic.theme
Labels: patch, size/xs

#198 D9 Readiness
  CHANGELOG.md
  UPGRADE.md
  composer.json
  stanford_basic.info.yml
  stanford_basic.theme
Labels: patch, size/xs

#196 D8CORE-2899: Updating the character line length to 100 from 70
  dist/css/components.css
  src/scss/components/wysiwyg/_line_length.scss
Labels: size/xs
