Repository SU-SWS/stanford_basic, pull requests merged in 2020-05, with the labels that each got.

#158 D8CORE-1869: Added circleci configuration
  .circleci/config.yml
  .github/auto-label.json
  .github/workflows/label.yml
Labels: size/xs

#160 outline instead of border
  src/scss/theme/menu/_local-tasks.scss
Labels: size/xs

#159 D8CORE-2004 JS Error in stanford_basic local tabs.
  dist/css/theme.css
  dist/js/base.js
  dist/js/behaviors.js
  src/js/base.js
  src/js/behaviors.js
  src/js/stanford_basic.behavior.js
  src/js/theme/menu/StickyHeaderOnScroll.js
  src/scss/theme/menu/_local-tasks.scss
Labels: size/s

#161 "8.x-4.x > 8.4.5
  .circleci/config.yml
  .github/auto-label.json
  .github/workflows/label.yml
  CHANGELOG.md
  dist/css/theme.css
  dist/js/behaviors.js
  src/js/behaviors.js
  src/js/stanford_basic.behavior.js
  src/js/theme/index.js
  src/js/theme/menu/StickyHeaderOnScroll.js
  src/js/theme/menu/index.js
  src/scss/theme/menu/_local-tasks.scss
  stanford_basic.info.yml
  stanford_basic.theme
  templates/menus/menu-local-tasks.html.twig
Labels: patch, size/s

#162 Reduce the z indexes to fix layout builder overlays
  dist/css/theme.css
  src/scss/theme/menu/_local-tasks.scss
Labels: patch, size/xs
