Repository SU-SWS/stanford_basic, pull requests merged in 2021-03, with the labels that each got.

#214 D8CORE-3473 Fix the mobile menu search attributes
  dist/js/behaviors.js
  src/js/stanford_basic.behavior.js
Labels: size/xs

#217 "8.x-5.x 8.5.0
  CHANGELOG.md
  UPGRADE.md
  composer.json
  dist/css/components.css
  dist/js/behaviors.js
  src/js/stanford_basic.behavior.js
  src/scss/components/index.scss
  src/scss/components/paragraphs/_paragraph--events.scss
  src/scss/components/paragraphs/_paragraph--people.scss
  src/scss/components/stanford-page/_page-title.scss
  src/scss/theme/index.scss
  stanford_basic.info.yml
  templates/core/field.html.twig
  templates/navigation/toolbar.html.twig
Labels: minor, size/s

#219 D8CORE-3502: Hotfix for active, focus pseudoclasses on dropdown toggle
  CHANGELOG.md
  dist/css/components.css
  src/scss/components/multi-menu/_multi-menu.scss
  stanford_basic.info.yml
Labels: patch, size/xs

#220 8.5.3
  CHANGELOG.md
  dist/css/components.css
  dist/js/behaviors.js
  src/js/stanford_basic.behavior.js
  stanford_basic.info.yml
Labels: patch, size/xs

#218 D8CORE-3474: unsetting the white color to fix for a11y
  dist/css/components.css
  src/scss/components/masthead/_wrapper.scss
Labels: size/xs

#222 D8CORE-3682: Fixed word wrapping on long menu titles
  dist/css/components.css
  package-lock.json
  src/scss/components/multi-menu/_multi-menu.scss
Labels: size/xl
