Repository SU-SWS/stanford_basic, pull requests merged in 2021-05, with the labels that each got.

#226 D8CORE-4037: fixed word wrapping with very long menu items
  dist/css/components.css
  src/scss/admin/_menu.scss
  src/scss/components/multi-menu/_multi-menu.scss
  templates/menus/macros/nav-menu.twig
Labels: size/xs

#227 D8CORE-3502 - a11y fixes for nav menu
  dist/css/base.css
  dist/js/base.js
  dist/js/behaviors.js
  src/js/components/secondary-nav/buttons/SubNavToggle.js
  src/js/components/secondary-nav/common/events/OnEsc.js
  src/scss/components/multi-menu/_multi-menu.scss
  templates/menus/macros/nav-menu.twig
  templates/menus/macros/secondary-nav-menu.twig
Labels: size/xs

#228 "8.x-5.x 8.5.5
  CHANGELOG.md
  dist/css/base.css
  dist/css/components.css
  dist/js/base.js
  dist/js/behaviors.js
  src/js/components/secondary-nav/buttons/SubNavToggle.js
  src/js/components/secondary-nav/common/events/OnEsc.js
  src/scss/admin/_menu.scss
  src/scss/components/multi-menu/_multi-menu.scss
  stanford_basic.info.yml
  templates/menus/macros/nav-menu.twig
  templates/menus/macros/secondary-nav-menu.twig
Labels: patch, size/xs

#230 D8CORE-2494 Add "Back to Top" button
  dist/css/base.css
  dist/css/components.css
  dist/css/theme.css
  dist/js/base.js
  dist/js/behaviors.js
  package-lock.json
  src/js/stanford_basic.behavior.js
  src/scss/theme/_back_to_top.scss
  src/scss/theme/index.scss
  templates/page.html.twig
Labels: size/xl
