Repository SU-SWS/stanford_basic, pull requests merged in 2021-09, with the labels that each got.

#241 D8CORE-4714: adding the title description to the secondary menu links
  dist/assets/fonts/fa-brands-400.eot
  dist/assets/fonts/fa-brands-400.ttf
  dist/assets/fonts/fa-brands-400.woff
  dist/assets/fonts/fa-brands-400.woff2
  dist/assets/fonts/fa-regular-400.eot
  dist/assets/fonts/fa-regular-400.ttf
  dist/assets/fonts/fa-regular-400.woff
  dist/assets/fonts/fa-regular-400.woff2
  dist/assets/fonts/fa-solid-900.eot
  dist/assets/fonts/fa-solid-900.ttf
  dist/assets/fonts/fa-solid-900.woff
  dist/assets/fonts/fa-solid-900.woff2
  dist/assets/svg/fa-brands-400.svg
  dist/assets/svg/fa-regular-400.svg
  dist/assets/svg/fa-solid-900.svg
  dist/css/base.css
  dist/css/ckeditor.css
  dist/css/components.css
  dist/css/user_login.css
  dist/js/base.js
  templates/menus/macros/secondary-nav-menu.twig
Labels: size/s

#244 D8CORE-4768: removing the conditional to put back into news module
  dist/css/components.css
  src/scss/components/filter-menu/_filter-menu.scss
Labels: size/xs

#245 8.5.10
  CHANGELOG.md
  dist/css/components.css
  src/scss/components/filter-menu/_filter-menu.scss
  stanford_basic.info.yml
Labels: patch, size/xs
